- name: install and run apachi service
  hosts: web
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: running  serivces
    serivces:
      name: httpd
      state: started
      enabled: yes