- name: install and run apachi service
  hosts: web
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: running  services
    services:
      name: httpd
      state: started
      enabled: yes