- name: install and run nfs service
  hosts: web
  become: yes
  tasks: 
  - name: install package
    ansible.builtin.package:
      name: nfs
      state: present
  - name: run nfs
    ansible.builtin.service:
      name: nfs
      state: started