- name: check data types
  hosts: localhost
  become: yes
  vars:
    NAME: Anilkumar # Key pair
    Skills:
    - Devops
    - Shell
    - Ansible
    - Linux
    Experience: # Experience is map, it contain key value pairs
      DevOps: 7
      AWS: 4
      Docker: 3
    Trainer: True # Boolean
  tasks:
  - name: print pairs
    debug:
    msg: "name: {{NAME}}"

  - name: print list
    debug:
    msg: "Skills: {{Skills}}"

  - name: print map
    debug:
    msg: "Experience: {{Experience}}"

  - name: print Boolean
    debug:
    msg: "Trainer: {{Trainer}}"

   
