- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install/uninstall packages
    ansible.builtin.package:
     name: "{{item.name}}"
     state: "{{state.name}}"
    loop:
    - { name: 'git', state: 'present' }
    - { name: 'mysql', state: 'absent' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'nginx', state: 'present' }